<?php use Events\Entity\Registration; ?>
<div class="col-lg-8">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Event Signup</h2>
        </div>
        <div class="panel-body">
    <form class="form-horizontal" action="/events/signup/<?= $event->getId() ?>" method="POST">
    <input type="hidden" name="registration[event_id]" value="<?= $event->getId() ?>" />
    <input type="hidden" name="registration[registration_time]" value="<?= date(Registration::DATE_FORMAT) ?>" />
    <fieldset>

		<!-- //*** FORMS AND FIELDSETS LAB: refactor to use Zend\Form object -->
        <!-- Form Name -->
        <legend>Event Signup</legend>

        Please fill out all items as appropriate.

        <div class="control-group">
            <label class="control-label">Event</label>
            <div class="controls">
                <span class=""><?= $event->getName() ?></span>
            </div>
        </div>


        <!-- Text input-->
        <div class="control-group">
            <label class="control-label"><?= $this->formLabel($this->regForm->get('first_name')); ?></label>
            <div class="controls">
				<?= $this->formText($this->regForm->get('first_name')); ?>
            </div>
        </div>

        <!-- Text input-->
        <div class="control-group">
            <label class="control-label"><?= $this->formLabel($this->regForm->get('last_name')); ?></label>
            <div class="controls">
				<?= $this->formText($this->regForm->get('last_name')); ?>
            </div>
        </div>

        <div id="ticket-list" data-ticket-count="1">

            <div class="control-group">
                <label class="control-label"><?= $this->formLabel($this->regForm->get('attendee_0')->get('name_on_ticket[]')); ?></label>
                <div class="controls">
					<?php for ($x = 0; $x < \Events\Module::MAX_NAMES_PER_TICKET; $x++) : ?>
						<?= $this->formMultiText($this->regForm->get('attendee_' . $x)->get('name_on_ticket[]')); ?>
                    <?php endfor; ?>
                </div>
            </div>
			
        </div>

        <!-- Button -->
        <div class="control-group">
            <label class="control-label"></label>
            <div class="controls">
                <button id="" name="" class="btn btn-success">Sign Up!</button>
            </div>
        </div>


    </fieldset>
    </form>
    </div>
</div>
